FROM ubuntu AS nodemgrbuildbase
RUN apt update
RUN apt install -y git g++ make zlib1g-dev libssl-dev libboost-all-dev cmake

FROM nodemgrbuildbase AS casa
WORKDIR /src
#RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN git clone https://github.com/Microsoft/cpprestsdk.git casa
WORKDIR /src/casa/Release/build.release
RUN cmake .. -DCMAKE_BUILD_TYPE=Release
RUN make -l $(nproc) -j $(nproc)
RUN make install
