FROM ubuntu AS nodemgrbuildbase
RUN apt update
RUN apt install -y git g++ make zlib1g-dev libssl-dev libboost-all-dev cmake

FROM nodemgrbuildbase AS casa
WORKDIR /src
ADD https://api.github.com/repos/EvanCui/cpprestsdk/compare/master...HEAD /dev/null
RUN git clone https://github.com/EvanCui/cpprestsdk.git casa
WORKDIR /src/casa/Release/build.release
RUN cmake .. -DCMAKE_BUILD_TYPE=Release
RUN make -l $(nproc) -j $(nproc)
RUN make install

FROM casa AS final
WORKDIR /src
ADD https://api.github.com/repos/EvanCui/spdlog/compare/master...HEAD /dev/null
RUN git clone https://github.com/EvanCui/spdlog.git
ENTRYPOINT ["bash"]

