FROM evancui/nodemanager:nmbuildbase AS nodemgrrelease
WORKDIR /src
ADD https://api.github.com/repos/coolmay/whpc-linux-communicator/compare/master...HEAD /dev/null
RUN git clone https://github.com/coolmay/whpc-linux-communicator.git
WORKDIR /src/whpc-linux-communicator/nodemanager
ENV TERM=xterm
RUN make -f Makefile-Acm release -l $(nproc) -j $(nproc)
RUN make -f Makefile-Acm release

FROM microsoft/aspnetcore-build:2.0 AS hpcacmbuild
WORKDIR /src
ADD https://api.github.com/repos/Azure/hpcpack-acm/compare/release/v1...HEAD /dev/null
RUN git clone https://github.com/Azure/hpcpack-acm.git
WORKDIR /src/hpcpack-acm
RUN git checkout release/v1
WORKDIR /src/hpcpack-acm/src/Services/NodeAgent
RUN dotnet publish -c Release -r linux-x64 --self-contained -o /app/NodeAgent

FROM evancui/nodemanager:nmexecbase AS final
COPY --from=nodemgrrelease /src/whpc-linux-communicator/nodemanager/bin/release/ /opt/acmnodemanager
RUN mv -f /opt/acmnodemanager/common-acm.sh /opt/acmnodemanager/common.sh
COPY --from=hpcacmbuild /app/NodeAgent/ /app/NodeAgent/
COPY ./VMExtension/ /app/
COPY ./publish/ /publish/
RUN rm -rf filters
RUN rm -rf certs
RUN rm -rf logs
RUN echo '\n\
./nodemanager & \n\
cd /app/NodeAgent/ \n\
./NodeAgent "$@" \n\
' > start.sh
RUN echo '{ \n\
    "HeartbeatUri":"http://localhost:8080/api/callback/computenodereported", \n\
    "TaskCompletionUri":"http://localhost:8080/api/callback/taskcompleted", \n\
    "RegisterUri":"http://localhost:8080/api/callback/registerrequested", \n\
    "ListeningUri":"http://0.0.0.0:40000", \n\
    "Debug":false, \n\
    "LogLevel":1 \n\
}' > nodemanager.json
ENTRYPOINT ["bash", "./start.sh"]
